### ISSUE TITLE
Жесткая просадка ФПС после 5 минут игры.

### ISSUE THREAD

**Issue by Windows1seven** [LambdaRP/Bug-Tracker-LambdaRP#12]
День добрый, при игре больше чем 5 минут замечается высокая просадка ФПС, с последующим крашем ( просто зависает игра, не реагирую ни на какие комманды ) в моем случае. Общался с несколькими людьми, с похожими проблемами. Возможно проблема у ВСЕХ.

Лично в моем случае - железо/интернет соединение оптимальны для игры в GTA V/FiveM (первый раз за более чем год игры создаю подобную тему). Знаю что FiveM жрет в 2 раза больше чем сингл, но даже уменьшение разрешения, и отключение всевозможных настроек графики и сведение их к минимуму не помогает. 

До этого вроде была подобная проблема, с просадкой памяти - но она выявляла себя после 2-3 часов игры, сейчас же намного меньше.

P.S. Один человек рассуждал что подобные просадки ФПС могут быть из-за "скрипта/мода и т.п" который убирает дроп оружия с НПС. Я не шарю, но вдруг...

**Comment by XXanderWP** [comment]
Большая часть кода уже переписана, что позволило стабилизировать FPS. Будут вестись дальнейшие работы в эту сторону.
