### ISSUE TITLE
Слишком высокие цены на автомобили

### ISSUE THREAD

**Issue by KatzzzGG** [LambdaRP/Bug-Tracker-LambdaRP#15]
ИМХО
Как по мне, цены на автомобили слишком завышены. 
Чтобы позволить приобрести себе бюджетное авто (не корыто за 15к), игроку нужно фармить как минимум пару дней, что не есть хорошо, так как во время этого фарма он минимизирует коммуникацию с другими игроками, так как точки фарма/переработки/сбыта находятся далеко от мест скопления игроков. А после обновления с лицензиями вообще стало не совсем ясно как можно зарабатывать "хорошие" деньги. 
Был бы очень признателен, если бы вы пересмотрели цены на транспорт. Да, я не спорю что автомобили из премиум сегмента не должны стоить мало, но ведь есть уйма автомобилей которые как по своему внешнему виду, так и по характеристикам не соответствуют своей высокой цене. 

Спасибо вам заранее, надеюсь на вас.

**Comment by XXanderWP** [comment]
Цены будут немного снижены в обновлении
