### ISSUE TITLE
Автосалон. Покупка авто.(крит.)

### ISSUE THREAD

**Issue by panik1337** [LambdaRP/Bug-Tracker-LambdaRP#20]
При покупке авто - деньги с баланса банка переводятся в карман и не списываются с баланса персонажа. При этом автомобиль куплен.

Также нельзя рассчитаться наличкой в автосалоне.  20 000 на руках- машина за 15 000 не покупается. 
"Недостаточно денег"

**Comment by XXanderWP** [comment]
Будет исправлено в обновлении
