### ISSUE TITLE
Команда /try

### ISSUE THREAD

**Issue by Shekerbeshka** [LambdaRP/Bug-Tracker-LambdaRP#43]
Предлагаю сделать на сервере команду try,всё таки из неё можно сделать много разных отыгровок,к примеру в том же самом гетто при игре в баскетбол,думаю вы поняли мою мысль))

**Comment by XXanderWP** [comment]
Имеется в виду действие с рандомным шансом на удачу?

**Comment by quanuhs** [comment]
XXanderWP, да. Все верно.

/try закинул мяч в кольцо.
Quanuhs закинул мяч в кольцо | удачно / неудачно.

**Comment by XXanderWP** [comment]
Выполнено и будет добавлено на сервере после теста при следующем обновлении
