### ISSUE TITLE
32 x 32 

### ISSUE THREAD

**Issue by quanuhs** [LambdaRP/Bug-Tracker-LambdaRP#50]
Предлагаю разделить два сервера на два территории. Таким образом,  территория города - сервер 1, а территория загородом - сервер 2.
По-возможности сделать переход с одного сервера на другой через определенную точку (проход). Можно,например кпп.
Люди на сервере 1 не смогут поехать загород не пройдя опр. Точку, которая переподключит их ко 2 серверу.

За городом будет следить полиция, а за округом Блейн - шерифы

**Comment by XXanderWP** [comment]
Не актуально, дублирующий сервер отключён.
