### ISSUE TITLE
Машины для гос.фракций

### ISSUE THREAD

**Issue by panik1337** [LambdaRP/Bug-Tracker-LambdaRP#8]
Первые две уже давно просят...

Джип Шерифа
Крузер без опознавательных знаков
Броневик  с водометом для разгона демонстраций(Был добавлен с последним обновлением 5m)

**Comment by XXanderWP** [comment]
Транспорт для гос.служащих уже готовится, к сожалению мы не успели ввести всё, что было задумано, однако со временем это будет сделано

**Comment by XXanderWP** [comment]
Выполнено

**Comment by panik1337** [comment]
Unmarked cruiser не был добавлен. Тачка нужна для детективов и фбр.
