### ISSUE TITLE
Регулировка громкости рации.

### ISSUE THREAD

**Issue by Windows1seven** [LambdaRP/Bug-Tracker-LambdaRP#9]
Слишком громкая рация. Регулировка звука отсутствует...

Ничего не мешает конечно перейти хотя бы гос структурам на ТС, ДС, да хоть на скайп. Но... Хз даже.

**Comment by XXanderWP** [comment]
В течении суток-двух будет настройка по регулировке громкости.

**Comment by XXanderWP** [comment]
Выполнено
